@startuml
title WarmHouse Context Diagram

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person_Ext(user, "User")
System(warmhouse, "Warm House")
System(sensors, 'Sensors')
Rel(user, warmhouse, "Check temperature and manage the heating")
Rel(warmhouse, sensors, "Get temperature, set heating mode")
Rel(sensors, warmhouse, "Session")
@enduml